<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sukeerthsahana" failures="10" tests="76" name="dsAlgoTests.ArrayTest" time="501.542" errors="2" timestamp="2025-02-18T00:22:13 CST" skipped="12">
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToArrayInPython" time="4.704"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToArrayInPython" time="6.230"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToArrayUsingList" time="4.573"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToArrayUsingList" time="5.580"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToBasicOperationInList" time="5.498"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToBasicOperationInList" time="4.039"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToApplicationOfArray" time="4.719"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToApplicationOfArray" time="5.686"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToArrayInPythonTryEditor" time="7.501"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToArrayInPythonTryEditor" time="5.620"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToArrayUsingListTryEditor" time="6.868"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToArrayUsingListTryEditor" time="5.215"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToBasicOperationInListTryEditor" time="7.040"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToBasicOperationInListTryEditor" time="5.841"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToApplicationOfArrayTryEditor" time="6.047"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToApplicationOfArrayTryEditor" time="6.942"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor" time="5.939">
    <skipped/>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor" time="7.307">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor(ArrayTest.java:123)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor" time="5.534">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor(ArrayTest.java:123)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor" time="6.724">
    <skipped/>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor" time="6.732">
    <skipped/>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor" time="7.753">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor(ArrayTest.java:134)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor" time="6.303">
    <skipped/>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor" time="6.164">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor(ArrayTest.java:134)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor" time="7.150">
    <skipped/>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor" time="6.289">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor(ArrayTest.java:146)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor" time="5.848">
    <skipped/>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor" time="8.794">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor(ArrayTest.java:146)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor" time="5.816">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor(ArrayTest.java:157)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor" time="6.916">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor(ArrayTest.java:157)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor" time="5.689">
    <skipped/>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor" time="7.051">
    <skipped/>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="5.652"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="8.864"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="6.829"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="6.622"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="5.761"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="7.294"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="6.399"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="6.190"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="6.432"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="8.642"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="6.285"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="6.912"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="6.118"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="6.314"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="4.803"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="7.133"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="6.314"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="6.971"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="7.492"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="7.051"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="7.133"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="6.358"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="6.386"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="6.698"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="8.100"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="7.612"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="7.192"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="6.531"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="7.271"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="6.301"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="9.150"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="7.403"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="7.203"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="7.751">
    <failure message="Output mismatch for section: Arrays in Python expected [Submission Successful] but found [Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Output mismatch for section: Arrays in Python expected [Submission Successful] but found [Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton(ArrayTest.java:196)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- PracticeQuestionVaildAndInvalidDataWithSubmitButton -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="7.092">
    <skipped/>
  </testcase> <!-- PracticeQuestionVaildAndInvalidDataWithSubmitButton -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="8.456"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="7.697">
    <skipped/>
  </testcase> <!-- PracticeQuestionVaildAndInvalidDataWithSubmitButton -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="4.674">
    <skipped/>
  </testcase> <!-- PracticeQuestionVaildAndInvalidDataWithSubmitButton -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="6.833">
    <skipped/>
  </testcase> <!-- PracticeQuestionVaildAndInvalidDataWithSubmitButton -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="7.142"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="6.832">
    <error message="Invalid Practice Question: Squares of a Sorted Array" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Invalid Practice Question: Squares of a Sorted Array
at dsAlgoPages.ArrayPage.PracticeQuestion(ArrayPage.java:187)
at dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton(ArrayTest.java:192)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- PracticeQuestionVaildAndInvalidDataWithSubmitButton -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="7.265"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="7.292">
    <failure message="Output mismatch for section: Arrays in Python expected [Submission Successful] but found [Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Output mismatch for section: Arrays in Python expected [Submission Successful] but found [Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton(ArrayTest.java:196)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- PracticeQuestionVaildAndInvalidDataWithSubmitButton -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="4.980">
    <error message="Invalid Practice Question: Squares of a Sorted Array" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Invalid Practice Question: Squares of a Sorted Array
at dsAlgoPages.ArrayPage.PracticeQuestion(ArrayPage.java:187)
at dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton(ArrayTest.java:192)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- PracticeQuestionVaildAndInvalidDataWithSubmitButton -->
  <system-out/>
</testsuite> <!-- dsAlgoTests.ArrayTest -->
