<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SF0QLDR" failures="5" tests="32" name="dsAlgoTests.ArrayTest" time="211.540" errors="1" timestamp="2025-02-05T18:23:00 EST" skipped="0">
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="9.750"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="8.446"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="5.721"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="6.506">
    <error message="Invalid Practice Question: Squares of a Sorted Array" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Invalid Practice Question: Squares of a Sorted Array
at dsAlgoPages.ArrayPage.PracticeQuestion(ArrayPage.java:187)
at dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton(ArrayTest.java:186)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </error>
  </testcase> <!-- PracticeQuestionVaildAndInvalidDataWithSubmitButton -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor" time="4.751">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor(ArrayTest.java:144)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="8.887"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToArrayInPython" time="4.929"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor" time="6.498">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor(ArrayTest.java:134)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="7.544"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="5.892"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToArrayUsingListTryEditor" time="4.681"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="5.763"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="7.412"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToApplicationOfArray" time="6.293"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="7.390"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="9.618"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="6.553"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="7.338"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToBasicOperationInList" time="6.048"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor" time="7.655">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor(ArrayTest.java:124)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="8.071">
    <failure message="Output mismatch for section: Arrays in Python expected [Submission Successful] but found [Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Output mismatch for section: Arrays in Python expected [Submission Successful] but found [Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton(ArrayTest.java:190)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- PracticeQuestionVaildAndInvalidDataWithSubmitButton -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToApplicationOfArrayTryEditor" time="9.388"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToArrayInPythonTryEditor" time="7.816"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="7.554"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor" time="5.623">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor(ArrayTest.java:154)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToArrayUsingList" time="3.991"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="4.616"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="4.634"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="verifyCodeExecutionForArraySections" time="5.884"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithSubmitButton" time="5.910"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="PracticeQuestionVaildAndInvalidDataWithRunButton" time="5.041"/>
  <system-out/>
  <testcase classname="dsAlgoTests.ArrayTest" name="navigateToBasicOperationInListTryEditor" time="5.337"/>
  <system-out/>
</testsuite> <!-- dsAlgoTests.ArrayTest -->
